spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    driverClassName: org.postgresql.Driver
    username: demo
    password: demo
    hikari:
      maximum-pool-size: 10
      max-lifetime: 3600000
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    user: demo_liquibase
    password: demo
    enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true